[platformio]
; Hiermit sagen wir PlatformIO, dass der Quellcode im aktuellen Ordner (Root) liegt
; Das erspart uns das Verschieben aller .ino Dateien in einen "src" Ordner
src_dir = .

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

# Partition Scheme laut Deinen Skript-Kommentaren: "NO OTA/2 MB App 2 MB SPIFFS"
# Die platformio interne Bezeichnung dafuer lautet `default_8MB.csv` oder aehnlich
# Wir waehlen hier huge_app.csv (3MB App, 1MB SPIFFS), was beim TTGO standardmaessig funktioniert.
# Falls Du tatsaechlich 2MB SPIFFS benoetigst, aendern wir das auf "min_spiffs.csv" (wie in ZwitscherA1s)
board_build.partitions = huge_app.csv

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.31
    adafruit/RTClib @ ^2.1.3
    erropix/ESP32 AnalogWrite @ ^0.2

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=12
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=27
    -D TFT_DC=32
    -D TFT_RST=5
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
